using Sperry.MxS.Core.Common.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Sperry.MxS.Reporting.Common.Constants
{
    public static class SurveyFormatConstant
    {

        public static readonly Dictionary<string, MxSFormatType> SolutionFormats = new Dictionary
           <string, MxSFormatType>
            {
                {"RunNumber", MxSFormatType.Null},
                {"SerialNumber", MxSFormatType.Null},
                {"PrimaryOrSecondary", MxSFormatType.Null},
                {"StartDepth", MxSFormatType.MeasuredDepthDistance},
                {"EndDepth", MxSFormatType.MeasuredDepthDistance},
                {"Service", MxSFormatType.Null},
                {"InclinationSolution", MxSFormatType.Null},
                {"SolutionType", MxSFormatType.Null},
                {"Pumps", MxSFormatType.Null},
                {"LastEditedBy", MxSFormatType.MeasuredDepthDistance},
                {"LastEditedTime", MxSFormatType.MeasuredDepthDistance},
                {"CreatedBy", MxSFormatType.MeasuredDepthDistance},
                {"CreatedTime", MxSFormatType.Null}
           };


        public static readonly Dictionary<string, MxSFormatType> RunFormats = new Dictionary
            <string, MxSFormatType>
            {
                {"RunNumber", MxSFormatType.Null},
                {"ToolType", MxSFormatType.Null},
                {"SerialNumber", MxSFormatType.Null},
                {"PrimaryOrSecondary", MxSFormatType.Null},
                {"StartTime", MxSFormatType.Null},
                {"EndTime", MxSFormatType.Null},
                {"StartDepth", MxSFormatType.MeasuredDepthDistance},
                {"EndDepth", MxSFormatType.MeasuredDepthDistance},
                {"NonMagAboveSensor", MxSFormatType.MeasuredDepthDistance},
                {"NonMagBelowSensor", MxSFormatType.MeasuredDepthDistance},
                {"DistanceToBit", MxSFormatType.MeasuredDepthDistance},
                {"ToolfaceOffset", MxSFormatType.Null},
                { "InclinationTolerance", MxSFormatType.Null},
                { "AzimuthLongCollarTolerance", MxSFormatType.Null},
                { "CreatedTime", MxSFormatType.Null},
                { "CreatedBy", MxSFormatType.Null},
                { "LastEditedBy", MxSFormatType.Null},
                { "LastEditedTime", MxSFormatType.Null}
           };

        public static readonly Dictionary<string, MxSFormatType> Formats = new Dictionary<string, MxSFormatType>
        {
            {"Depth", MxSFormatType.MeasuredDepthDistance},
            {"Gx", MxSFormatType.GxGyGz},
            {"Gy", MxSFormatType.GxGyGz},
            {"Gz", MxSFormatType.GxGyGz},
            {"Bx", MxSFormatType.BxByBz},
            {"By", MxSFormatType.BxByBz},
            {"Bz", MxSFormatType.BxByBz},
            {"Dipe", MxSFormatType.MagneticDipAngle},
            {"Be", MxSFormatType.MagneticFieldStrength},
            {"Decle", MxSFormatType.MagneticDeclination},
            {"Conve", MxSFormatType.GridConvergence}
        };

        public static readonly Dictionary<string, MxSFormatType> RawSheetFormats = new Dictionary<string, MxSFormatType>
        {
            {"Depth", MxSFormatType.MeasuredDepthDistance},
            {"Gx", MxSFormatType.GxGyGz},
            {"Gy", MxSFormatType.GxGyGz},
            {"Gz", MxSFormatType.GxGyGz},
            {"Gte", MxSFormatType.Gravity6},
            {"Inc", MxSFormatType.Inclination},
            {"Hsd", MxSFormatType.GxGyGz},
            {"HsdSpread", MxSFormatType.GxGyGz},
            {"Gtm", MxSFormatType.Gravity6},
            {"GxyInc", MxSFormatType.Inclination},
            {"GzInc", MxSFormatType.Inclination}
        };

        public static readonly Dictionary<string, Dictionary<string, MxSFormatType>> SheetFormats = new Dictionary
            <string, Dictionary<string, MxSFormatType>>
            {
                {
                    "WbIcaRawGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"Gx", MxSFormatType.GxGyGz},
                        {"Gy", MxSFormatType.GxGyGz},
                        {"Gz", MxSFormatType.GxGyGz},
                        {"Gte", MxSFormatType.Gravity6},
                        {"Inc", MxSFormatType.Inclination},
                        {"Hsd", MxSFormatType.GxGyGz},
                        {"HsdSpread", MxSFormatType.GxGyGz},
                        {"Gtm", MxSFormatType.Gravity6},
                        {"GxyInc", MxSFormatType.Inclination},
                        {"GzInc", MxSFormatType.Inclination}
                    }
                },

                {
                    "WbIcaTfcGrid", new Dictionary<string,  MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"dGx", MxSFormatType.GxGyGz},
                        {"dGy", MxSFormatType.GxGyGz},
                        {"dGz", MxSFormatType.GxGyGz},
                        {"dGxAcc", MxSFormatType.GxGyGz},
                        {"dGyAcc", MxSFormatType.GxGyGz},
                        {"dGzAcc", MxSFormatType.GxGyGz},
                        {"Gx", MxSFormatType.GxGyGz},
                        {"Gy", MxSFormatType.GxGyGz},
                        {"Gz", MxSFormatType.GxGyGz},
                        {"Inc", MxSFormatType.Inclination},
                        {"Hsd", MxSFormatType.GxGyGz},
                        {"Gt", MxSFormatType.Gravity6},
                        {"dGxMax", MxSFormatType.GxGyGz},
                        {"dGxMin", MxSFormatType.GxGyGz},
                        {"dGyMax", MxSFormatType.GxGyGz},
                        {"dGyMin", MxSFormatType.GxGyGz}
                    }
                },

                {
                    "WbIcaTxyGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"dGx", MxSFormatType.GxGyGz},
                        {"dGy", MxSFormatType.GxGyGz},
                        {"K", MxSFormatType.GxGyGz},
                        {"dGxAcc", MxSFormatType.GxGyGz},
                        {"dGyAcc", MxSFormatType.GxGyGz},
                        {"KAcc", MxSFormatType.GxGyGz},
                        {"Gx", MxSFormatType.GxGyGz},
                        {"Gy", MxSFormatType.GxGyGz},
                        {"Gz", MxSFormatType.GxGyGz},
                        {"Inc", MxSFormatType.Inclination},
                        {"Hsd", MxSFormatType.GxGyGz},
                        {"Gt", MxSFormatType.Gravity6},
                        {"dGxMax", MxSFormatType.GxGyGz},
                        {"dGxMin", MxSFormatType.GxGyGz},
                        {"dGyMax", MxSFormatType.GxGyGz},
                        {"dGyMin", MxSFormatType.GxGyGz}
                    }
                },

                {
                    "WbIcaSfeGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"dGx", MxSFormatType.GxGyGz},
                        {"dGy", MxSFormatType.GxGyGz},
                        {"dGz", MxSFormatType.GxGyGz},
                        {"sGx", MxSFormatType.SFPercent},
                        {"sGy", MxSFormatType.SFPercent},
                        {"dGxAcc", MxSFormatType.GxGyGz},
                        {"dGyAcc", MxSFormatType.GxGyGz},
                        {"dGzAcc", MxSFormatType.GxGyGz},
                        {"sGxAcc", MxSFormatType.SFPercent},
                        {"sGyAcc", MxSFormatType.SFPercent},
                        {"Gx", MxSFormatType.GxGyGz},
                        {"Gy", MxSFormatType.GxGyGz},
                        {"Gz", MxSFormatType.GxGyGz},
                        {"Inc", MxSFormatType.Inclination},
                        {"Hsd", MxSFormatType.GxGyGz},
                        {"Gt", MxSFormatType.Gravity6},
                        {"dGxMax", MxSFormatType.GxGyGz},
                        {"dGxMin", MxSFormatType.GxGyGz},
                        {"dGyMax", MxSFormatType.GxGyGz},
                        {"dGyMin", MxSFormatType.GxGyGz},
                        {"sGxMax", MxSFormatType.SFPercent},
                        {"sGxMin", MxSFormatType.SFPercent},
                        {"sGyMin", MxSFormatType.SFPercent}
                    }
                },

                {
                    "WbIcaDiyGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"dGx", MxSFormatType.GxGyGz},
                        {"dGy", MxSFormatType.GxGyGz},
                        {"dGz", MxSFormatType.GxGyGz},
                        {"sGx", MxSFormatType.SFPercent},
                        {"sGy", MxSFormatType.SFPercent},
                        {"Gx", MxSFormatType.GxGyGz},
                        {"Gy", MxSFormatType.GxGyGz},
                        {"Gz", MxSFormatType.GxGyGz},
                        {"Inc", MxSFormatType.Inclination},
                        {"Hsd", MxSFormatType.GxGyGz},
                        {"Gt", MxSFormatType.Gravity6}
                    }
                },

                {
                    "WbCazRawDatasGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"Gx", MxSFormatType.GxGyGz},
                        {"Gy", MxSFormatType.GxGyGz},
                        {"Gz", MxSFormatType.GxGyGz},
                        {"Bx", MxSFormatType.BxByBz},
                        {"By", MxSFormatType.BxByBz},
                        {"Bz", MxSFormatType.BxByBz},
                        {"dBzSc", MxSFormatType.BxByBz},
                        {"dBzMAv", MxSFormatType.BxByBz},
                        {"Inclination", MxSFormatType.Inclination},
                        {"Highside", MxSFormatType.GxGyGz},
                        {"HsSpread", MxSFormatType.GxGyGz},
                        {"AzSc", MxSFormatType.Azimuth},
                        {"AzLc", MxSFormatType.Azimuth},
                        {"AzLcMAv", MxSFormatType.Azimuth},
                        {"Gt", MxSFormatType.Gravity6},
                        {"Bc", MxSFormatType.MagneticFieldStrength},
                        {"Dipc", MxSFormatType.MagneticDipAngle},
                        {"BcMav", MxSFormatType.MagneticFieldStrength},
                        {"DipcMav", MxSFormatType.MagneticDipAngle},
                        {"dB", MxSFormatType.MagneticFieldStrength},
                        {"dDip", MxSFormatType.MagneticDipAngle},
                        {"BtDip", MxSFormatType.MagneticFieldStrength},
                        {"dBMav", MxSFormatType.MagneticFieldStrength},
                        {"dDipMav", MxSFormatType.MagneticDipAngle},
                        {"BtDipMav", MxSFormatType.MagneticFieldStrength},
                        {"BGmMavVisible", MxSFormatType.MagneticDipAngle},
                        {"SxyVisible", MxSFormatType.Percent3},
                        {"SxyMavVisible", MxSFormatType.Percent3}
                    }
                },

                {
                    "WbCazTfcGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"dBx", MxSFormatType.BxByBz},
                        {"dBy", MxSFormatType.BxByBz},
                        {"dBz", MxSFormatType.BxByBz},
                        {"dBxAcc", MxSFormatType.BxByBz},
                        {"dByAcc", MxSFormatType.BxByBz},
                        {"dBzAcc", MxSFormatType.BxByBz},
                        {"dBzSc", MxSFormatType.BxByBz},
                        {"dBzMAv", MxSFormatType.BxByBz},
                        {"AzSc", MxSFormatType.Azimuth},
                        {"AzLc", MxSFormatType.Azimuth},
                        {"AzLcMAv", MxSFormatType.Azimuth},
                        {"Bc", MxSFormatType.MagneticFieldStrength},
                        {"Dipc", MxSFormatType.MagneticDipAngle},
                        {"BcMav", MxSFormatType.MagneticFieldStrength},
                        {"DipcMav", MxSFormatType.MagneticDipAngle},
                        {"dB", MxSFormatType.MagneticFieldStrength},
                        {"dDip", MxSFormatType.MagneticDipAngle},
                        {"BtDip", MxSFormatType.MagneticFieldStrength},
                        {"dBMav", MxSFormatType.MagneticFieldStrength},
                        {"dDipMav", MxSFormatType.MagneticDipAngle},
                        {"BtDipMav", MxSFormatType.MagneticFieldStrength},
                        {"BGmMavVisible", MxSFormatType.MagneticDipAngle},
                        {"SxyVisible", MxSFormatType.Percent3},
                        {"SxyMavVisible", MxSFormatType.Percent3},
                        {"dBxMax", MxSFormatType.BxByBz},
                        {"dBxMin", MxSFormatType.BxByBz},
                        {"dByMax", MxSFormatType.BxByBz},
                        {"dByMin", MxSFormatType.BxByBz}
                    }
                },

                {
                    "WbCazTxyGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"dBx", MxSFormatType.BxByBz},
                        {"dBy", MxSFormatType.BxByBz},
                        {"K", MxSFormatType.BxByBz},
                        {"dBxAcc", MxSFormatType.BxByBz},
                        {"dByAcc", MxSFormatType.BxByBz},
                        {"KAcc", MxSFormatType.BxByBz},
                        {"dBzSc", MxSFormatType.Azimuth},
                        {"dBzMAv", MxSFormatType.Azimuth},
                        {"AzSc", MxSFormatType.Azimuth},
                        {"AzLc", MxSFormatType.Azimuth},
                        {"AzLcMAv", MxSFormatType.Azimuth},
                        {"Bc", MxSFormatType.MagneticFieldStrength},
                        {"Dipc", MxSFormatType.MagneticDipAngle},
                        {"BcMav", MxSFormatType.MagneticFieldStrength},
                        {"DipcMav", MxSFormatType.MagneticDipAngle},
                        {"dB", MxSFormatType.MagneticFieldStrength},
                        {"dDip", MxSFormatType.MagneticDipAngle},
                        {"BtDip", MxSFormatType.MagneticFieldStrength},
                        {"dBMav", MxSFormatType.MagneticFieldStrength},
                        {"dDipMav", MxSFormatType.MagneticDipAngle},
                        {"BtDipMav", MxSFormatType.MagneticFieldStrength},
                        {"BGmMavVisible", MxSFormatType.MagneticDipAngle},
                        {"SxyVisible", MxSFormatType.Percent3},
                        {"SxyMavVisible", MxSFormatType.Percent3},
                        {"dBxMax", MxSFormatType.BxByBz},
                        {"dBxMin", MxSFormatType.BxByBz},
                        {"dByMax", MxSFormatType.BxByBz},
                        {"dByMin", MxSFormatType.BxByBz}
                    }
                },

                {
                    "WbCazSfeGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"dBx", MxSFormatType.BxByBz},
                        {"dBy", MxSFormatType.BxByBz},
                        {"dBz", MxSFormatType.BxByBz},
                        {"Sx", MxSFormatType.Percent3},
                        {"Sy", MxSFormatType.Percent3},
                        {"dBxAcc", MxSFormatType.BxByBz},
                        {"dByAcc", MxSFormatType.BxByBz},
                        {"dBzAcc", MxSFormatType.BxByBz},
                        {"SxAcc", MxSFormatType.Percent3},
                        {"SyAcc", MxSFormatType.Percent3},
                        {"dBzSc", MxSFormatType.Azimuth},
                        {"dBzMAv", MxSFormatType.Azimuth},
                        {"AzSc", MxSFormatType.Azimuth},
                        {"AzLc", MxSFormatType.Azimuth},
                        {"AzLcMAv", MxSFormatType.Azimuth},
                        {"Bc", MxSFormatType.MagneticFieldStrength},
                        {"Dipc", MxSFormatType.MagneticDipAngle},
                        {"BcMav", MxSFormatType.MagneticFieldStrength},
                        {"DipcMav", MxSFormatType.MagneticDipAngle},
                        {"dB", MxSFormatType.MagneticFieldStrength},
                        {"dDip", MxSFormatType.MagneticDipAngle},
                        {"BtDip", MxSFormatType.MagneticFieldStrength},
                        {"dBMav", MxSFormatType.MagneticFieldStrength},
                        {"dDipMav", MxSFormatType.MagneticDipAngle},
                        {"BtDipMav", MxSFormatType.MagneticFieldStrength},
                        {"BGmVisible", MxSFormatType.MagneticDipAngle},
                        {"BGmMavVisible", MxSFormatType.MagneticDipAngle},
                        {"dBxMax", MxSFormatType.BxByBz},
                        {"dBxMin", MxSFormatType.BxByBz},
                        {"dByMax", MxSFormatType.BxByBz},
                        {"dByMin", MxSFormatType.BxByBz},
                        {"SxMax", MxSFormatType.Percent3},
                        {"SxMin", MxSFormatType.Percent3},
                        {"SyMax", MxSFormatType.Percent3},
                        {"SyMin", MxSFormatType.Percent3}
                    }
                },

                {
                    "WbCazDiyGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"dBx", MxSFormatType.BxByBz},
                        {"dBy", MxSFormatType.BxByBz},
                        {"dBz", MxSFormatType.BxByBz},
                        {"Sx", MxSFormatType.Percent3},
                        {"Sy", MxSFormatType.Percent3},
                        {"BzMisAng", MxSFormatType.Azimuth},
                        {"BzMisDir", MxSFormatType.Azimuth},
                        {"dBzSc", MxSFormatType.Azimuth},
                        {"dBzMAv", MxSFormatType.Azimuth},
                        {"AzSc", MxSFormatType.Azimuth},
                        {"AzLc", MxSFormatType.Azimuth},
                        {"AzLcMAv", MxSFormatType.Azimuth},
                        {"Bc", MxSFormatType.MagneticFieldStrength},
                        {"Dipc", MxSFormatType.MagneticDipAngle},
                        {"BcMav", MxSFormatType.MagneticFieldStrength},
                        {"DipcMav", MxSFormatType.MagneticDipAngle},
                        {"dB", MxSFormatType.MagneticFieldStrength},
                        {"dDip", MxSFormatType.MagneticDipAngle},
                        {"BtDip", MxSFormatType.MagneticFieldStrength},
                        {"dBMav", MxSFormatType.MagneticFieldStrength},
                        {"dDipMav", MxSFormatType.MagneticDipAngle},
                        {"BtDipMav", MxSFormatType.MagneticFieldStrength},
                        {"BGmVisible", MxSFormatType.MagneticDipAngle},
                        {"BGmMavVisible", MxSFormatType.MagneticDipAngle},
                        {"Sxy", MxSFormatType.Percent3},
                        {"SxyMavVisible", MxSFormatType.Percent3}
                    }
                },

                {
                    "WbAziErrorLCGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"AziErrorInclination", MxSFormatType.Inclination},
                        {"AziErrorAzimuth", MxSFormatType.Azimuth},
                        {"AziErrorAzimuthMagnetic", MxSFormatType.Azimuth},
                        {"dAzdBz", MxSFormatType.MagneticDipAngle},
                        {"dAzSxy", MxSFormatType.MagneticDipAngle},
                        {"dAzBGm", MxSFormatType.MagneticDipAngle},
                        {"dAzTotal", MxSFormatType.MagneticDipAngle},
                        {"dDipdBz", MxSFormatType.MagneticDipAngle},
                        {"dDipSxy", MxSFormatType.MagneticDipAngle},
                        {"dDipBGm", MxSFormatType.MagneticDipAngle},
                        {"dDipTotal", MxSFormatType.MagneticDipAngle},
                        {"dBtdBz", MxSFormatType.MagneticFieldStrength},
                        {"dBtSxy", MxSFormatType.MagneticFieldStrength},
                        {"dBtBGm", MxSFormatType.MagneticFieldStrength},
                        {"dBtTotal", MxSFormatType.MagneticFieldStrength}
                    }
                },

                {
                    "WbAziErrorSCGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"AziErrorInclination", MxSFormatType.Inclination},
                        {"AziErrorAzimuth", MxSFormatType.Azimuth},
                        {"AziErrorAzimuthMagnetic", MxSFormatType.Azimuth},
                        {"dAzdDipePlus", MxSFormatType.MagneticDipAngle},
                        {"dAzdDipeMinus", MxSFormatType.MagneticDipAngle},
                        {"dAzdBePlus", MxSFormatType.MagneticDipAngle},
                        {"dAzdBeMinus", MxSFormatType.MagneticDipAngle},
                        {"dAzSxy", MxSFormatType.MagneticDipAngle},
                        {"dAzBGm", MxSFormatType.MagneticDipAngle},
                        {"dAzTotalPlus", MxSFormatType.MagneticDipAngle},
                        {"dAzTotalMinus", MxSFormatType.MagneticDipAngle},
                        {"dDipcdDipePlus", MxSFormatType.MagneticDipAngle},
                        {"dDipcdDipeMinus", MxSFormatType.MagneticDipAngle},
                        {"dDipcdBePlus", MxSFormatType.MagneticDipAngle},
                        {"dDipcdBeMinus", MxSFormatType.MagneticDipAngle},
                        {"dDipcSxy", MxSFormatType.MagneticDipAngle},
                        {"dDipcBGm", MxSFormatType.MagneticDipAngle},
                        {"dDipcTotalPlus", MxSFormatType.MagneticDipAngle},
                        {"dDipcTotalMinus", MxSFormatType.MagneticDipAngle},
                        {"dBtcdDipePlus", MxSFormatType.MagneticFieldStrength},
                        {"dBtcdDipeMinus", MxSFormatType.MagneticFieldStrength},
                        {"dBtcdBePlus", MxSFormatType.MagneticFieldStrength},
                        {"dBtcdBeMinus", MxSFormatType.MagneticFieldStrength},
                        {"dBtcSxy", MxSFormatType.MagneticFieldStrength},
                        {"dBtcBGm", MxSFormatType.MagneticFieldStrength},
                        {"dBtcTotalPlus", MxSFormatType.MagneticFieldStrength},
                        {"dBtcTotalMinus", MxSFormatType.MagneticFieldStrength},
                        {"dBzcdDipePlus", MxSFormatType.MagneticFieldStrength},
                        {"dBzcdDipeMinus", MxSFormatType.MagneticFieldStrength},
                        {"dBzcdBePlus", MxSFormatType.MagneticFieldStrength},
                        {"dBzcdBeMinus", MxSFormatType.MagneticFieldStrength},
                        {"dBzcSxy", MxSFormatType.MagneticFieldStrength},
                        {"dBzcBGm", MxSFormatType.MagneticFieldStrength},
                        {"dBzcTotalPlus", MxSFormatType.MagneticFieldStrength},
                        {"dBzcTotalMinus", MxSFormatType.MagneticFieldStrength}
                    }
                },

                {
                    "WbAziErrorLCPositionGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"AziErrorInclination", MxSFormatType.Inclination},
                        {"AziErrorAzimuth", MxSFormatType.Azimuth},
                        {"dBzNE", MxSFormatType.MeasuredDepthDistance},
                        {"SxyNE", MxSFormatType.MeasuredDepthDistance},
                        {"BGmNE", MxSFormatType.MeasuredDepthDistance},
                        {"dDecleNE", MxSFormatType.MeasuredDepthDistance},
                        {"TotalNE", MxSFormatType.MeasuredDepthDistance},
                        {"dBzEE", MxSFormatType.MeasuredDepthDistance},
                        {"SxyEE", MxSFormatType.MeasuredDepthDistance},
                        {"BGmEE", MxSFormatType.MeasuredDepthDistance},
                        {"dDecleEE", MxSFormatType.MeasuredDepthDistance},
                        {"TotalEE", MxSFormatType.MeasuredDepthDistance},
                        {"dBzLE", MxSFormatType.MeasuredDepthDistance},
                        {"SxyLE", MxSFormatType.MeasuredDepthDistance},
                        {"BGmLE", MxSFormatType.MeasuredDepthDistance},
                        {"dDecleLE", MxSFormatType.MeasuredDepthDistance},
                        {"TotalLE", MxSFormatType.MeasuredDepthDistance}
                    }
                },

                {
                    "WbAziErrorSCPositionGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"AziErrorInclination", MxSFormatType.Inclination},
                        {"AziErrorAzimuth", MxSFormatType.Azimuth},
                        {"dDipePlusNE", MxSFormatType.MeasuredDepthDistance},
                        {"dDipeMinusNE", MxSFormatType.MeasuredDepthDistance},
                        {"dBePlusNE", MxSFormatType.MeasuredDepthDistance},
                        {"dBeMinusNE", MxSFormatType.MeasuredDepthDistance},
                        {"SxyNE", MxSFormatType.MeasuredDepthDistance},
                        {"BGmNE", MxSFormatType.MeasuredDepthDistance},
                        {"dDecleNE", MxSFormatType.MeasuredDepthDistance},
                        {"TotalNEPlus", MxSFormatType.MeasuredDepthDistance},
                        {"TotalNEMinus", MxSFormatType.MeasuredDepthDistance},
                        {"dDipePlusEE", MxSFormatType.MeasuredDepthDistance},
                        {"dDipeMinusEE", MxSFormatType.MeasuredDepthDistance},
                        {"dBePlusEE", MxSFormatType.MeasuredDepthDistance},
                        {"dBeMinusEE", MxSFormatType.MeasuredDepthDistance},
                        {"SxyEE", MxSFormatType.MeasuredDepthDistance},
                        {"BGmEE", MxSFormatType.MeasuredDepthDistance},
                        {"dDecleEE", MxSFormatType.MeasuredDepthDistance},
                        {"TotalEEPlus", MxSFormatType.MeasuredDepthDistance},
                        {"TotalEEMinus", MxSFormatType.MeasuredDepthDistance},
                        {"dDipePlusLE", MxSFormatType.MeasuredDepthDistance},
                        {"dDipeMinusLE", MxSFormatType.MeasuredDepthDistance},
                        {"dBePlusLE", MxSFormatType.MeasuredDepthDistance},
                        {"dBeMinusLE", MxSFormatType.MeasuredDepthDistance},
                        {"SxyLE", MxSFormatType.MeasuredDepthDistance},
                        {"BGmLE", MxSFormatType.MeasuredDepthDistance},
                        {"dDecleLE", MxSFormatType.MeasuredDepthDistance},
                        {"TotalLEPlus", MxSFormatType.MeasuredDepthDistance},
                        {"TotalLEMinus", MxSFormatType.MeasuredDepthDistance}
                    }
                },

                {
                    "WbAziErrorPoistionGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"AziErrorInclination", MxSFormatType.Inclination},
                        {"AziErrorAzimuth", MxSFormatType.Azimuth},
                        {"North", MxSFormatType.MeasuredDepthDistance},
                        {"East", MxSFormatType.MeasuredDepthDistance},
                        {"Vertical", MxSFormatType.MeasuredDepthDistance},
                        {"Lateral", MxSFormatType.MeasuredDepthDistance}
                    }
                },

                {
                    "WbAziErrorInputGrid", new Dictionary<string, MxSFormatType>
                    {
                        {"Depth", MxSFormatType.MeasuredDepthDistance},
                        {"AziErrorInclination", MxSFormatType.Inclination},
                        {"AziErrorAzimuth", MxSFormatType.Azimuth},
                        {"Dipe", MxSFormatType.MagneticDipAngle},
                        {"Be", MxSFormatType.MagneticFieldStrength},
                        {"Decle", MxSFormatType.MagneticDeclination},
                        {"Conve", MxSFormatType.GridConvergence}
                    }
                }
            };


        public static readonly Dictionary<string, MxSFormatType> OriginalSurveyFormats = new Dictionary<string, MxSFormatType>
        {
            {"BhMeasured", MxSFormatType.MagneticFieldStrength},
            {"BtMeasured", MxSFormatType.MagneticFieldStrength},
            {"BvMeasured", MxSFormatType.MagneticFieldStrength},
            {"Bx", MxSFormatType.BxByBz},
            {"By", MxSFormatType.BxByBz},
            {"Bz", MxSFormatType.BxByBz},
            {"Depth", MxSFormatType.MeasuredDepthDistance},
            {"DipMeasured", MxSFormatType.MagneticDipAngle},
            {"GtRawQC", MxSFormatType.Gravity},
            {"Gx", MxSFormatType.GxGyGz},
            {"Gy", MxSFormatType.GxGyGz},
            {"Gz", MxSFormatType.GxGyGz},
            {"MWDInclination", MxSFormatType.Inclination},
            {"MWDLongCollar", MxSFormatType.Azimuth},
            {"MWDShortCollar", MxSFormatType.Azimuth},
            {"GxyInclination", MxSFormatType.Inclination},
            {"GxyzInclination", MxSFormatType.Inclination},
            {"GzInclination", MxSFormatType.Inclination},
            {"SagInclination", MxSFormatType.Inclination},
            {"Temperature", MxSFormatType.Temperature}
        };

        public static readonly Dictionary<string, MxSFormatType> PlanSurveyFormats = new Dictionary<string, MxSFormatType>
        {
            {"Depth", MxSFormatType.MeasuredDepthDistance},
            {"MWDInclination", MxSFormatType.Inclination},
            {"MWDShortCollar", MxSFormatType.Azimuth},
            {"NomBt", MxSFormatType.MagneticFieldStrength},
            {"NomDip", MxSFormatType.MagneticDipAngle},
            {"NomDeclination", MxSFormatType.MagneticDipAngle},
            {"NomGrid", MxSFormatType.MagneticDipAngle}
        };

        public static readonly Dictionary<string, MxSFormatType> RangingDeterminationFormats = new Dictionary
            <string, MxSFormatType>
            {
                {"RawSurvey.BhMeasured", MxSFormatType.MagneticFieldStrength},
                {"RawSurvey.BtMeasured", MxSFormatType.MagneticFieldStrength},
                {"RawSurvey.BvMeasured", MxSFormatType.MagneticFieldStrength},
                {"RawSurvey.Bx", MxSFormatType.BxByBz},
                {"RawSurvey.By", MxSFormatType.BxByBz},
                {"RawSurvey.Bz", MxSFormatType.BxByBz},
                {"RawSurvey.Depth", MxSFormatType.MeasuredDepthDistance},
                {"RawSurvey.DipMeasured", MxSFormatType.MagneticDipAngle},
                {"RawSurvey.GtRawQC", MxSFormatType.Gravity},
                {"RawSurvey.Gx", MxSFormatType.GxGyGz},
                {"RawSurvey.Gy", MxSFormatType.GxGyGz},
                {"RawSurvey.Gz", MxSFormatType.GxGyGz},
                {"RawSurvey.MWDInclination", MxSFormatType.Inclination},
                {"RawSurvey.MWDLongCollar", MxSFormatType.Azimuth},
                {"RawSurvey.MWDShortCollar", MxSFormatType.Azimuth},
                {"RawSurvey.GxyInclination", MxSFormatType.Inclination},
                {"RawSurvey.GxyzInclination", MxSFormatType.Inclination},
                {"RawSurvey.GzInclination", MxSFormatType.Inclination},
                {"SagInclination", MxSFormatType.Inclination},
                {"RawSurvey.Temperature", MxSFormatType.Temperature}
            };

        public static readonly Dictionary<string, MxSFormatType> WellSelectorFormats = new Dictionary<string, MxSFormatType>
        {
            {"Azimuth", MxSFormatType.Azimuth},
            {"Bt QC  Limit", MxSFormatType.MagneticFieldStrength},
            {"BtDip QC Limit", MxSFormatType.MagneticFieldStrength},
            {"Grid Coordinate System", MxSFormatType.GridConvergence},
            {"Gt QC Limit", MxSFormatType.Gravity},
            {"Height above PD", MxSFormatType.MagneticDipAngle},
            {"High Azi/Inc QC Limit", MxSFormatType.Inclination},
            {"Inclination", MxSFormatType.Inclination},
            {"Latitude", MxSFormatType.UnitlessTwoPrecision},
            {"Latitude Origin", MxSFormatType.MeasuredDepthDistance},
            {"Longitude origin", MxSFormatType.MeasuredDepthDistance},
            {"Low Azi/Inc QC Limit", MxSFormatType.Inclination},
            {"Declination", MxSFormatType.MagneticDeclination},
            {"MagDip", MxSFormatType.MagneticDipAngle},
            {"Magnetic Field Strength", MxSFormatType.MagneticFieldStrength},
            {"Magnetic Model", MxSFormatType.MagneticFieldStrength},
            {"MD", MxSFormatType.MeasuredDepthDistance},
            {"N/S Departure", MxSFormatType.MeasuredDepthDistance},
            {"North Reference", MxSFormatType.MeasuredDepthDistance},
            {"Northing/Y", MxSFormatType.NorthingEasting},
            {"Observes DST", MxSFormatType.MagneticFieldStrength},
            {"Rig", MxSFormatType.RigInclination},
            {"Survey Measured from", MxSFormatType.MagneticFieldStrength},
            {"TVD", MxSFormatType.MeasuredDepthDistance},
            {"Longitude", MxSFormatType.UnitlessTwoPrecision},
            {"GridConvergence", MxSFormatType.MagneticDipAngle},
            {"Easting/X", MxSFormatType.NorthingEasting},
            {"Elevation", MxSFormatType.MeasuredDepthDistance},
            {"Central Meridan", MxSFormatType.TotalCorrection},
            {"Dip QC Limit", MxSFormatType.MagneticDipAngle},
            {"Eccentricity squared", MxSFormatType.GridConvergence}, //doubt Grid System Special
			{"Elevation of PD above MSL", MxSFormatType.MeasuredDepthDistance},
            {"Elipsoid", MxSFormatType.TotalCorrection},
            {"False Easting", MxSFormatType.MeasuredDepthDistance},
            {"MeasuredDepth",MxSFormatType.MeasuredDepthDistance },
            {"Northing", MxSFormatType.Northing},
            {"Easting", MxSFormatType.Northing},
            {"False Northing", MxSFormatType.MeasuredDepthDistance}
        };

        public static readonly Dictionary<string, MxSFormatType> ASARulesFormats = new Dictionary
            <string, MxSFormatType>
            {
                {"AndOr", MxSFormatType.Null},
                {"Rule Name", MxSFormatType.Null},
                {"Equation 1", MxSFormatType.Null},
                {"Operator", MxSFormatType.Null},
                {"Equation 2", MxSFormatType.Null}
           };

        public static readonly Dictionary<string, MxSFormatType> IFR1BackCalculatorFormats = new Dictionary
            <string, MxSFormatType>
            {
                {"Well.Latitude", MxSFormatType.UnitlessTwoPrecision},
                {"Well.Longitude", MxSFormatType.UnitlessTwoPrecision},
                {"Well.Name", MxSFormatType.Null},
                {"Distance", MxSFormatType.UnitlessTwoPrecision},
                {"Well.Customer", MxSFormatType.Null},
                {"Well.Country", MxSFormatType.Null},
                {"WellName", MxSFormatType.Null},
                {"Output.Inputs.Count", MxSFormatType.Null},
                {"Output.DBeErrorEstimate",MxSFormatType.MagneticDipAngle},
                {"Output.DBeAccuracy", MxSFormatType.MagneticDipAngle},
                {"Output.DipeAccuracy",MxSFormatType.MagneticDipAngle},
                {"Output.DipeErrorEstimate", MxSFormatType.MagneticDipAngle},
                {"Depth", MxSFormatType.MeasuredDepthDistance},
                {"Gx", MxSFormatType.GxGyGz},
                {"Gy", MxSFormatType.GxGyGz},
                {"Gz", MxSFormatType.GxGyGz},
                {"Bx", MxSFormatType.BxByBz},
                {"By", MxSFormatType.BxByBz},
                {"Bz", MxSFormatType.BxByBz},
                {"NomBt", MxSFormatType.MagneticFieldStrength},
                {"NomBtDip", MxSFormatType.MagneticFieldStrength},
                {"NomDeclination", MxSFormatType.MagneticDipAngle},
                {"NomDip", MxSFormatType.MagneticDipAngle},
                {"SoldBx", MxSFormatType.MagneticFieldStrength},
                {"SoldBy", MxSFormatType.MagneticFieldStrength},
                {"SoldBz", MxSFormatType.MagneticFieldStrength},

            };

        public static readonly Dictionary<string, MxSFormatType> DerivedSurveyValuesFormats = new Dictionary
            <string, MxSFormatType>
            {
                {"IcaGoxy", MxSFormatType.Gravity},
                {"IcaGt", MxSFormatType.Gravity},
                {"IcaGx", MxSFormatType.Gravity},
                {"IcaGxyzInc", MxSFormatType.Goxy},
                {"IcaGy", MxSFormatType.Gravity},
                {"IcaGz", MxSFormatType.Gravity},
                {"IFR1Bh", MxSFormatType.MagneticFieldStrength},
                {"IFR1BhBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR1BtBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR1BtDipBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR1BtDipBzMeasured", MxSFormatType.MagneticFieldStrength},
                {"IFR1BvBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR1BzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR1Dec", MxSFormatType.MagneticDipAngle},
                {"IFR1Dip", MxSFormatType.MagneticDipAngle},
                {"IFR1DipBzCalc", MxSFormatType.MagneticDipAngle},
                {"IFR1EW", MxSFormatType.MeasuredDepthDistance},
                {"IFR1LC", MxSFormatType.MagneticDipAngle},
                {"IFR1NS", MxSFormatType.MeasuredDepthDistance},
                {"IFR1SC", MxSFormatType.MagneticDipAngle},
                {"IFR1TVD", MxSFormatType.MeasuredDepthDistance},
                {"IFR2Bh", MxSFormatType.MagneticFieldStrength},
                {"IFR2BhBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR2Bt", MxSFormatType.MagneticFieldStrength},
                {"IFR2BtBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR2BtDipBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR2BtDipBzMeasured", MxSFormatType.MagneticFieldStrength},
                {"IFR2Bv", MxSFormatType.MagneticFieldStrength},
                {"IFR2BvBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR2BzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR2Dec", MxSFormatType.MagneticDipAngle},
                {"IFR2Dip", MxSFormatType.MagneticDipAngle},
                {"IFR2DipBzCalc", MxSFormatType.MagneticDipAngle},
                {"IFR2EW", MxSFormatType.MeasuredDepthDistance},
                {"IFR2LC", MxSFormatType.Azimuth},
                {"IFR2NS", MxSFormatType.MeasuredDepthDistance},
                {"IFR2SC", MxSFormatType.Azimuth},
                {"IFR2TVD", MxSFormatType.MeasuredDepthDistance},
                {"MMBe", MxSFormatType.MagneticFieldStrength},
                {"MFMBh", MxSFormatType.MagneticFieldStrength},
                {"MFMBhBzCalc", MxSFormatType.MagneticFieldStrength},
                {"MFMBt", MxSFormatType.MagneticFieldStrength},
                {"MFMBtBzCalc", MxSFormatType.MagneticFieldStrength},
                {"MFMBtDipBzCalc", MxSFormatType.MagneticFieldStrength},
                {"MFMBtDipBzMeasured", MxSFormatType.MagneticFieldStrength},
                {"MFMBv", MxSFormatType.MagneticFieldStrength},
                {"MFMBvBzCalc", MxSFormatType.MagneticFieldStrength},
                {"MFMBzCalc", MxSFormatType.MagneticFieldStrength},
                {"MFMDec", MxSFormatType.MagneticDipAngle},
                {"MFMDip", MxSFormatType.MagneticDipAngle},
                {"MFMDipBzCalc", MxSFormatType.MagneticDipAngle},
                {"MMDipe", MxSFormatType.MagneticDipAngle},
                {"MFMEW", MxSFormatType.MeasuredDepthDistance},
                {"MFMLC", MxSFormatType.Azimuth},
                {"MFMNS", MxSFormatType.MeasuredDepthDistance},
                {"MFMSC", MxSFormatType.Azimuth},
                {"MMTotalDec", MxSFormatType.MagneticDipAngle},
                {"MFMTVD", MxSFormatType.MeasuredDepthDistance},
                {"CazAz", MxSFormatType.RigInclination},
                {"CazBh", MxSFormatType.MagneticFieldStrength},
                {"CazBt", MxSFormatType.MagneticFieldStrength},
                {"CazBtDip", MxSFormatType.MagneticFieldStrength},
                {"CazBv", MxSFormatType.MagneticFieldStrength},
                {"CazBx", MxSFormatType.MagneticFieldStrength},
                {"CazBy", MxSFormatType.MagneticFieldStrength},
                {"CazBz", MxSFormatType.MagneticFieldStrength},
                {"CazDip", MxSFormatType.RigInclination},
                {"CazEW", MxSFormatType.NorthingEasting},
                {"CazNS", MxSFormatType.NorthingEasting},
                {"CazTVD", MxSFormatType.NorthingEasting},
            };

        public static readonly Dictionary<string, MxSFormatType> CorrectedSurveyFormats = new Dictionary
            <string, MxSFormatType>
            {
                {"CorrectedSurvey.Depth", MxSFormatType.MeasuredDepthDistance},
                {"Gx", MxSFormatType.GxGyGz},
                {"Gy", MxSFormatType.GxGyGz},
                {"Gz", MxSFormatType.GxGyGz},
                {"Bx", MxSFormatType.BxByBz},
                {"By", MxSFormatType.BxByBz},
                {"Bz", MxSFormatType.BxByBz},
                {"Dipe", MxSFormatType.MagneticDipAngle},
                {"Be", MxSFormatType.MagneticFieldStrength},
                {"Decle", MxSFormatType.MagneticDeclination},
                {"Conve", MxSFormatType.GridConvergence},
                {"CorrectedSurvey.RigInclination", MxSFormatType.RigInclination},
                {"MWDInclination", MxSFormatType.RigInclination},
                {"SagInclination", MxSFormatType.RigInclination},
                {"MWDShortCollar", MxSFormatType.RigInclination},
                {"CorrectedSurvey.RigAzimuthSC", MxSFormatType.RigInclination},
                {"MWDLongCollar", MxSFormatType.RigInclination},
                {"CorrectedSurvey.RigAzimuthLC", MxSFormatType.RigInclination},
                {"CorrectedSurvey.RawSurvey.Temperature", MxSFormatType.Temperature},
                {"CorrectedSurvey.NomBt", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.NomDip", MxSFormatType.MagneticDipAngle},
                {"CorrectedSurvey.GtQcDelta", MxSFormatType.Gravity},
                {"CorrectedSurvey.BtQcDelta", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.DipQcDelta", MxSFormatType.RigInclination},
                {"CorrectedSurvey.BtDipQcDelta", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.AzRssDynamicLimit", MxSFormatType.RigInclination},
                {"CorrectedSurvey.BhMeasured", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.BtMeasured", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.BtRssDynamicLimit", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.BtLimit", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.QCLimits.BtLimit", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.BtDipRssDynamicLimit", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.BtDipLimit", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.QCLimits.BtDipLimit", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.BvMeasured", MxSFormatType.MagneticFieldStrength},
                {"CazAz", MxSFormatType.RigInclination},
                {"CazBh", MxSFormatType.MagneticFieldStrength},
                {"CazBt", MxSFormatType.MagneticFieldStrength},
                {"CazBtDip", MxSFormatType.MagneticFieldStrength},
                {"CazBv", MxSFormatType.MagneticFieldStrength},
                {"CazBx", MxSFormatType.MagneticFieldStrength},
                {"CazBy", MxSFormatType.MagneticFieldStrength},
                {"CazBz", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.SoldBz", MxSFormatType.MagneticFieldStrength },
                {"CazDip", MxSFormatType.RigInclination},
                {"CazEW", MxSFormatType.NorthingEasting},
                {"CazNS", MxSFormatType.NorthingEasting},
                {"CazTVD", MxSFormatType.NorthingEasting},
                {"CorrectedSurvey.DipMeasured", MxSFormatType.RigInclination},
                {"CorrectedSurvey.DipRssDynamicLimit", MxSFormatType.RigInclination},
                {"CorrectedSurvey.DipLimit", MxSFormatType.RigInclination},
                {"CorrectedSurvey.QCLimits.DipLimit", MxSFormatType.RigInclination},
                {"CorrectedSurvey.Goxy", MxSFormatType.Goxy},
                {"CorrectedSurvey.QCLimits.GtLimit", MxSFormatType.Gravity},
                {"GtRawQC", MxSFormatType.Gravity},
                {"CorrectedSurvey.GTotal", MxSFormatType.Gravity},
                {"IcaGoxy", MxSFormatType.Gravity},
                {"IcaGt", MxSFormatType.Gravity},
                {"IcaGx", MxSFormatType.Gravity},
                {"IcaGxyzInc", MxSFormatType.Goxy},
                {"IcaGy", MxSFormatType.Gravity},
                {"IcaGz", MxSFormatType.Gravity},
                {"IFR1Bh", MxSFormatType.MagneticFieldStrength},
                {"IFR1BhBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR1BtBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR1BtDipBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR1BtDipBzMeasured", MxSFormatType.MagneticFieldStrength},
                {"IFR1BvBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR1BzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR1Dec", MxSFormatType.MagneticDipAngle},
                {"IFR1Dip", MxSFormatType.MagneticDipAngle},
                {"IFR1DipBzCalc", MxSFormatType.MagneticDipAngle},
                {"IFR1EW", MxSFormatType.MeasuredDepthDistance},
                {"IFR1LC", MxSFormatType.MagneticDipAngle},
                {"IFR1NS", MxSFormatType.MeasuredDepthDistance},
                {"IFR1SC", MxSFormatType.MagneticDipAngle},
                {"IFR1TVD", MxSFormatType.MeasuredDepthDistance},
                {"IFR2Bh", MxSFormatType.MagneticFieldStrength},
                {"IFR2BhBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR2Bt", MxSFormatType.MagneticFieldStrength},
                {"IFR2BtBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR2BtDipBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR2BtDipBzMeasured", MxSFormatType.MagneticFieldStrength},
                {"IFR2Bv", MxSFormatType.MagneticFieldStrength},
                {"IFR2BvBzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR2BzCalc", MxSFormatType.MagneticFieldStrength},
                {"IFR2Dec", MxSFormatType.MagneticDipAngle},
                {"IFR2Dip", MxSFormatType.MagneticDipAngle},
                {"IFR2DipBzCalc", MxSFormatType.MagneticDipAngle},
                {"IFR2EW", MxSFormatType.MeasuredDepthDistance},
                {"IFR2LC", MxSFormatType.Azimuth},
                {"IFR2NS", MxSFormatType.MeasuredDepthDistance},
                {"IFR2SC", MxSFormatType.Azimuth},
                {"IFR2TVD", MxSFormatType.MeasuredDepthDistance},
                {"MMBe", MxSFormatType.MagneticFieldStrength},
                {"MFMBh", MxSFormatType.MagneticFieldStrength},
                {"MFMBhBzCalc", MxSFormatType.MagneticFieldStrength},
                {"MFMBt", MxSFormatType.MagneticFieldStrength},
                {"MFMBtBzCalc", MxSFormatType.MagneticFieldStrength},
                {"MFMBtDipBzCalc", MxSFormatType.MagneticFieldStrength},
                {"MFMBtDipBzMeasured", MxSFormatType.MagneticFieldStrength},
                {"MFMBv", MxSFormatType.MagneticFieldStrength},
                {"MFMBvBzCalc", MxSFormatType.MagneticFieldStrength},
                {"MFMBzCalc", MxSFormatType.MagneticFieldStrength},
                {"MFMDec", MxSFormatType.MagneticDipAngle},
                {"MFMDip", MxSFormatType.MagneticDipAngle},
                {"MFMDipBzCalc", MxSFormatType.MagneticDipAngle},
                {"MMDipe", MxSFormatType.MagneticDipAngle},
                {"MFMEW", MxSFormatType.MeasuredDepthDistance},
                {"MFMLC", MxSFormatType.Azimuth},
                {"MFMNS", MxSFormatType.MeasuredDepthDistance},
                {"MFMSC", MxSFormatType.Azimuth},
                {"MMTotalDec", MxSFormatType.MagneticDipAngle},
                {"MFMTVD", MxSFormatType.MeasuredDepthDistance},
                {"CorrectedSurvey.NomBtDip", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.NomDeclination", MxSFormatType.MagneticDipAngle},
                {"CorrectedSurvey.NomGrid", MxSFormatType.MagneticDipAngle},
                {"CorrectedSurvey.NomGt", MxSFormatType.Gravity},
                {"CorrectedSurvey.ObservatoryBTRaw", MxSFormatType.MagneticFieldStrength},
                {"CorrectedSurvey.ObservatoryDecRaw", MxSFormatType.MagneticDipAngle},
                {"CorrectedSurvey.ObservatoryDipRaw", MxSFormatType.MagneticDipAngle},
                {"CorrectedSurvey.GxyInclination", MxSFormatType.Azimuth},
                {"CorrectedSurvey.GxyzInclination", MxSFormatType.Azimuth},
                {"CorrectedSurvey.GzInclination", MxSFormatType.Azimuth},
                {"Sigma", MxSFormatType.Azimuth},
                {"CorrectedSurvey.SolAzm", MxSFormatType.Azimuth},
                {"SolBt", MxSFormatType.MagneticFieldStrength},
                {"SolBtDip", MxSFormatType.MagneticFieldStrength},
                {"SolDip", MxSFormatType.MagneticDipAngle},
                {"SolGt", MxSFormatType.Gravity},
                {"CorrectedSurvey.SolInc", MxSFormatType.Inclination},
                {"CorrectedSurvey.GravityToolFace", MxSFormatType.Inclination},
                {"CorrectedSurvey.Solution.Run.ToolfaceOffset", MxSFormatType.Azimuth},
                {"CorrectedSurvey.UncertaintySigmaN", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintySigmaH", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintySigmaL", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintySigmaV", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintySigmaA", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintySigmaE", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintyBiasA", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintyBiasE", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintyBiasH", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintyBiasL", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintyBiasN", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintyBiasV", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintyCorrHL", MxSFormatType.UnitlessFourPrecision},
                {"CorrectedSurvey.UncertaintyCorrHA", MxSFormatType.UnitlessFourPrecision},
                {"CorrectedSurvey.UncertaintyCorrLA", MxSFormatType.UnitlessFourPrecision},
                {"CorrectedSurvey.UncertaintyCovEE", MxSFormatType.UncertaintyCovValue},
                {"CorrectedSurvey.UncertaintyCovEV", MxSFormatType.UncertaintyCovValue},
                {"CorrectedSurvey.UncertaintyCovNE", MxSFormatType.UncertaintyCovValue},
                {"CorrectedSurvey.UncertaintyCovNN", MxSFormatType.UncertaintyCovValue},
                {"CorrectedSurvey.UncertaintyCovNV", MxSFormatType.UncertaintyCovValue},
                {"CorrectedSurvey.UncertaintyCovVV", MxSFormatType.UncertaintyCovValue},
                {"CorrectedSurvey.UncertaintyHMajSA", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintyHMinSA", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintySemiAx1", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintySemiAx2", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintySemiAx3", MxSFormatType.Uncertainty},
                {"CorrectedSurvey.UncertaintyRotAng", MxSFormatType.Azimuth},
                {"CorrectedSurvey.TVDss", MxSFormatType.MeasuredDepthDistance },
                {"CorrectedSurvey.DCTVDss", MxSFormatType.MeasuredDepthDistance },
                {"CorrectedSurvey.TVD", MxSFormatType.MeasuredDepthDistance },
                {"CorrectedSurvey.NorthSouth", MxSFormatType.MeasuredDepthDistance},
                {"CorrectedSurvey.EastWest", MxSFormatType.MeasuredDepthDistance},
                {"CorrectedSurvey.CourseLength", MxSFormatType.MeasuredDepthDistance},
                {"CorrectedSurvey.Latitude", MxSFormatType.UnitlessTwoPrecision },
                {"CorrectedSurvey.Longitude", MxSFormatType.UnitlessTwoPrecision }
            };

        public static readonly Dictionary<string, MxSFormatType> ReportFormats = new Dictionary
            <string, MxSFormatType>
        {
            {"Azimuth", MxSFormatType.Azimuth},
            { "Depth", MxSFormatType.MeasuredDepthDistance},
            {"AzRssDynamicLimit", MxSFormatType.RigInclination},
            {"BGGMBTotal", MxSFormatType.MagneticFieldStrength },
            {"BGGMDeclination", MxSFormatType.MagneticDeclination },
            {"BGGMDip", MxSFormatType.MagneticDipAngle },
            {"BGGMTotalCorrection", MxSFormatType.TotalCorrection},
            {"Be", MxSFormatType.MagneticFieldStrength},
            {"BhMeasured", MxSFormatType.MagneticFieldStrength},
            {"Bt QC  Limit", MxSFormatType.MagneticFieldStrength},
            {"BtDip QC Limit", MxSFormatType.MagneticFieldStrength},
            {"BtDipLimit", MxSFormatType.MagneticFieldStrength},
            {"BtDipQcDelta", MxSFormatType.MagneticFieldStrength},
            {"BtDipRssDynamicLimit", MxSFormatType.MagneticFieldStrength},
            {"BtLimit", MxSFormatType.MagneticFieldStrength},
            {"BtMeasured", MxSFormatType.MagneticFieldStrength},
            {"BtQcDelta", MxSFormatType.MagneticFieldStrength},
            {"BtRssDynamicLimit", MxSFormatType.MagneticFieldStrength},
            {"BvMeasured", MxSFormatType.MagneticFieldStrength},
            {"Bx", MxSFormatType.BxByBz},
            {"By", MxSFormatType.BxByBz},
            {"Bz", MxSFormatType.BxByBz},
            {"CABtOffset", MxSFormatType.MagneticFieldStrength },
            {"CADecOffset", MxSFormatType.MagneticDeclination },
            {"CADipOffset", MxSFormatType.MagneticDipAngle },
            {"CazAz", MxSFormatType.RigInclination},
            {"CazBh", MxSFormatType.MagneticFieldStrength},
            {"CazBt", MxSFormatType.MagneticFieldStrength},
            {"CazBtDip", MxSFormatType.MagneticFieldStrength},
            {"CazBv", MxSFormatType.MagneticFieldStrength},
            {"CazBx", MxSFormatType.MagneticFieldStrength},
            {"CazBy", MxSFormatType.MagneticFieldStrength},
            {"CazBz", MxSFormatType.MagneticFieldStrength},
            {"CazDip", MxSFormatType.RigInclination},
            {"CazEW", MxSFormatType.NorthingEasting},
            {"CazNS", MxSFormatType.NorthingEasting},
            {"CazTVD", MxSFormatType.NorthingEasting},
            {"Central Meridan", MxSFormatType.TotalCorrection},
            {"Conve", MxSFormatType.GridConvergence},
            {"DBx", MxSFormatType.MagneticFieldStrength },
            {"DBy", MxSFormatType.MagneticFieldStrength },
            {"DBz", MxSFormatType.MagneticFieldStrength },
            {"DEC", MxSFormatType.MagneticDipAngle },
            {"Decle", MxSFormatType.MagneticDeclination},
            {"Declination", MxSFormatType.MagneticDeclination},
            {"DepthUnit", MxSFormatType.MeasuredDepthDistance },
            {"Dip QC Limit", MxSFormatType.MagneticDipAngle},
            {"Dip", MxSFormatType.MagneticDipAngle },
            {"DipLimit", MxSFormatType.RigInclination},
            {"DipMeasured", MxSFormatType.MagneticDipAngle},
            {"DipQcDelta", MxSFormatType.RigInclination},
            {"DipRssDynamicLimit", MxSFormatType.RigInclination},
            {"Dipe", MxSFormatType.MagneticDipAngle},
            {"DistanceToBit", MxSFormatType.MeasuredDepthDistance },
            {"Easting", MxSFormatType.MeasuredDepthDistance},
            {"Easting/X", MxSFormatType.NorthingEasting},
            {"Eccentricity squared", MxSFormatType.GridConvergence}, //doubt Grid System Special
			{"Elevation of PD above MSL", MxSFormatType.MeasuredDepthDistance},
            {"Elevation", MxSFormatType.MeasuredDepthDistance},
            {"Elipsoid", MxSFormatType.TotalCorrection},
            {"EndDepth", MxSFormatType.MeasuredDepthDistance },
            {"False Easting", MxSFormatType.MeasuredDepthDistance},
            {"False Northing", MxSFormatType.MeasuredDepthDistance},
            {"GTotal", MxSFormatType.Gravity},
            {"Goxy", MxSFormatType.Goxy},
            {"GravityToolFace", MxSFormatType.Inclination},
            {"Grid Coordinate System", MxSFormatType.GridConvergence},
            {"GridConvergence", MxSFormatType.MagneticDipAngle},
            {"Gt QC Limit", MxSFormatType.Gravity},
            {"GtLimit", MxSFormatType.Gravity},
            {"GtQcDelta", MxSFormatType.Gravity},
            {"GtRawQC", MxSFormatType.Gravity},
            {"Gx", MxSFormatType.GxGyGz},
            {"GxyInclination", MxSFormatType.Inclination},
            {"GxyzInclination", MxSFormatType.Inclination},
            {"Gy", MxSFormatType.GxGyGz},
            {"Gz", MxSFormatType.GxGyGz},
            {"GzInclination", MxSFormatType.Inclination},
            {"Height above PD", MxSFormatType.MagneticDipAngle },
            {"High Azi/Inc QC Limit", MxSFormatType.Inclination },
            {"IFR1Bh", MxSFormatType.MagneticFieldStrength},
            {"IFR1BhBzCalc", MxSFormatType.MagneticFieldStrength},
            {"IFR1BtBzCalc", MxSFormatType.MagneticFieldStrength},
            {"IFR1BtDipBzCalc", MxSFormatType.MagneticFieldStrength},
            {"IFR1BtDipBzMeasured", MxSFormatType.MagneticFieldStrength},
            {"IFR1BvBzCalc", MxSFormatType.MagneticFieldStrength},
            {"IFR1BzCalc", MxSFormatType.MagneticFieldStrength},
            {"IFR1Dec", MxSFormatType.MagneticDipAngle},
            {"IFR1Dip", MxSFormatType.MagneticDipAngle},
            {"IFR1DipBzCalc", MxSFormatType.MagneticDipAngle},
            {"IFR1EW", MxSFormatType.MeasuredDepthDistance},
            {"IFR1LC", MxSFormatType.MagneticDipAngle},
            {"IFR1NS", MxSFormatType.MeasuredDepthDistance},
            {"IFR1SC", MxSFormatType.MagneticDipAngle},
            {"IFR1TVD", MxSFormatType.MeasuredDepthDistance},
            {"IFR2Bh", MxSFormatType.MagneticFieldStrength},
            {"IFR2BhBzCalc", MxSFormatType.MagneticFieldStrength},
            {"IFR2Bt", MxSFormatType.MagneticFieldStrength},
            {"IFR2BtBzCalc", MxSFormatType.MagneticFieldStrength},
            {"IFR2BtDipBzCalc", MxSFormatType.MagneticFieldStrength},
            {"IFR2BtDipBzMeasured", MxSFormatType.MagneticFieldStrength},
            {"IFR2Bv", MxSFormatType.MagneticFieldStrength},
            {"IFR2BvBzCalc", MxSFormatType.MagneticFieldStrength},
            {"IFR2BzCalc", MxSFormatType.MagneticFieldStrength},
            {"IFR2Dec", MxSFormatType.MagneticDipAngle},
            {"IFR2Dip", MxSFormatType.MagneticDipAngle},
            {"IFR2DipBzCalc", MxSFormatType.MagneticDipAngle},
            {"IFR2EW", MxSFormatType.MeasuredDepthDistance},
            {"IFR2LC", MxSFormatType.Azimuth},
            {"IFR2NS", MxSFormatType.MeasuredDepthDistance},
            {"IFR2SC", MxSFormatType.Azimuth},
            {"IFR2TVD", MxSFormatType.MeasuredDepthDistance},
            {"IFRBTotal", MxSFormatType.MagneticFieldStrength },
            {"IFRDip", MxSFormatType.MagneticDipAngle },
            {"IcaGoxy", MxSFormatType.Gravity},
            {"IcaGt", MxSFormatType.Gravity},
            {"IcaGx", MxSFormatType.Gravity},
            {"IcaGxyzInc", MxSFormatType.Goxy},
            {"IcaGy", MxSFormatType.Gravity},
            {"IcaGz", MxSFormatType.Gravity},
            {"IcarusDGx", MxSFormatType.MilliG2 },
            {"IcarusDGy", MxSFormatType.MilliG2 },
            {"IcarusDGz", MxSFormatType.MilliG2 },
            {"IcarusSFGx", MxSFormatType.Percent3 },
            {"IcarusSFGy", MxSFormatType.Percent3 },
            {"IfrDeclination", MxSFormatType.MagneticDeclination },
            {"IfrTotalCorrection", MxSFormatType.TotalCorrection },
            {"Inclination", MxSFormatType.Inclination},
            {"Latitude Origin", MxSFormatType.MeasuredDepthDistance},
            {"Latitude", MxSFormatType.Null},
            {"Longitude origin", MxSFormatType.MeasuredDepthDistance},
            {"Longitude", MxSFormatType.Null},
            {"Low Azi/Inc QC Limit", MxSFormatType.Inclination},
            {"MD", MxSFormatType.MeasuredDepthDistance},
            {"MFMBh", MxSFormatType.MagneticFieldStrength},
            {"MFMBhBzCalc", MxSFormatType.MagneticFieldStrength},
            {"MFMBt", MxSFormatType.MagneticFieldStrength},
            {"MFMBtBzCalc", MxSFormatType.MagneticFieldStrength},
            {"MFMBtDipBzCalc", MxSFormatType.MagneticFieldStrength},
            {"MFMBtDipBzMeasured", MxSFormatType.MagneticFieldStrength},
            {"MFMBv", MxSFormatType.MagneticFieldStrength},
            {"MFMBvBzCalc", MxSFormatType.MagneticFieldStrength},
            {"MFMBzCalc", MxSFormatType.MagneticFieldStrength},
            {"MFMDec", MxSFormatType.MagneticDipAngle},
            {"MFMDip", MxSFormatType.MagneticDipAngle},
            {"MFMDipBzCalc", MxSFormatType.MagneticDipAngle},
            {"MFMEW", MxSFormatType.MeasuredDepthDistance},
            {"MFMLC", MxSFormatType.Azimuth},
            {"MFMNS", MxSFormatType.MeasuredDepthDistance},
            {"MFMSC", MxSFormatType.Azimuth},
            {"MFMTVD", MxSFormatType.MeasuredDepthDistance},
            {"MMBe", MxSFormatType.MagneticFieldStrength},
            {"MMDipe", MxSFormatType.MagneticDipAngle},
            {"MMTotalDec", MxSFormatType.MagneticDipAngle},
            {"MWDInclination", MxSFormatType.RigInclination},
            {"MWDLongCollar", MxSFormatType.Azimuth},
            {"MWDShortCollar", MxSFormatType.RigInclination},
            {"MagDip", MxSFormatType.MagneticDipAngle},
            {"Magnetic Field Strength", MxSFormatType.MagneticFieldStrength},
            {"Magnetic Model", MxSFormatType.MagneticFieldStrength},
            {"MagneticDeclination", MxSFormatType.MagneticDeclination },
            {"MagneticDipAngle", MxSFormatType.MagneticDipAngle },
            {"MagneticFieldStrength", MxSFormatType.MagneticFieldStrength },
            {"MeasuredDepth",MxSFormatType.MeasuredDepthDistance },
            {"N/S Departure", MxSFormatType.MeasuredDepthDistance},
            {"NomBt", MxSFormatType.MagneticFieldStrength},
            {"NomBtDip", MxSFormatType.MagneticFieldStrength},
            {"NomDeclination", MxSFormatType.MagneticDipAngle},
            {"NomDip", MxSFormatType.MagneticDipAngle},
            {"DipQcMax", MxSFormatType.MagneticDipAngle},
            {"DipQcMin", MxSFormatType.MagneticDipAngle},
            {"NomGrid", MxSFormatType.MagneticDipAngle},
            {"NomGt", MxSFormatType.Gravity},
            {"NonMagAboveSensor", MxSFormatType.MeasuredDepthDistance },
            {"NonMagBelowSensor", MxSFormatType.MeasuredDepthDistance },
            {"North Reference", MxSFormatType.MeasuredDepthDistance},
            {"Northing", MxSFormatType.MeasuredDepthDistance},
            {"Northing/Y", MxSFormatType.NorthingEasting},
            {"ObsSiteBTotal", MxSFormatType.Percent3 },
            {"ObsSiteDeclination", MxSFormatType.Inclination },
            {"ObsSiteDip", MxSFormatType.MagneticDipAngle },
            {"ObservatoryBTRaw", MxSFormatType.MagneticFieldStrength},
            {"ObservatoryDecRaw", MxSFormatType.MagneticDipAngle},
            {"ObservatoryDipRaw", MxSFormatType.MagneticDipAngle},
            {"Observes DST", MxSFormatType.MagneticFieldStrength},
            {"RawSurvey.Temperature", MxSFormatType.Temperature},
            {"RefBTotal", MxSFormatType.MagneticFieldStrength },
            {"RefDeclination", MxSFormatType.MagneticDeclination },
            {"RefDip", MxSFormatType.MagneticDipAngle},
            {"Rig", MxSFormatType.RigInclination},
            {"RigAzimuthLC", MxSFormatType.RigInclination},
            {"RigAzimuthSC", MxSFormatType.RigInclination},
            {"RigInclination", MxSFormatType.RigInclination},
            {"SFBx", MxSFormatType.Percent3 },
            {"SFBy", MxSFormatType.Percent3 },
            {"SFBz", MxSFormatType.Percent3 },
            {"SISA", MxSFormatType.Gravity},
            {"SagInclination", MxSFormatType.RigInclination},
            {"Sigma", MxSFormatType.Azimuth},
            {"SolAzm", MxSFormatType.Azimuth},
            {"SolBt", MxSFormatType.MagneticFieldStrength},
            {"SolBtDip", MxSFormatType.MagneticFieldStrength},
            {"SolDip", MxSFormatType.MagneticDipAngle},
            {"SolGt", MxSFormatType.Gravity},
            {"SolInc", MxSFormatType.Inclination},
            {"StartDepth", MxSFormatType.MeasuredDepthDistance },
            {"Survey Measured from", MxSFormatType.MagneticFieldStrength},
            {"TVD", MxSFormatType.MeasuredDepthDistance},
            {"Temperature", MxSFormatType.Temperature},
            {"ToolfaceOffset", MxSFormatType.Azimuth },
            {"VerticalDepth", MxSFormatType.MeasuredDepthDistance },
            {"TotalCorrection", MxSFormatType.TotalCorrection },
            {"SolBv",MxSFormatType.MagneticFieldStrength },
            {"SolBh",MxSFormatType.MagneticFieldStrength },
            {"NomBv",MxSFormatType.MagneticFieldStrength },
            {"NomBh",MxSFormatType.MagneticFieldStrength },
            {"UncertaintySigmaN", MxSFormatType.Uncertainty},
            {"UncertaintySigmaH", MxSFormatType.Uncertainty},
            {"UncertaintySigmaL", MxSFormatType.Uncertainty},
            {"UncertaintySigmaV", MxSFormatType.Uncertainty},
            {"UncertaintySigmaA", MxSFormatType.Uncertainty},
            {"UncertaintySigmaE", MxSFormatType.Uncertainty},
            {"UncertaintyBiasA", MxSFormatType.Uncertainty},
            {"UncertaintyBiasE", MxSFormatType.Uncertainty},
            {"UncertaintyBiasH", MxSFormatType.Uncertainty},
            {"UncertaintyBiasL", MxSFormatType.Uncertainty},
            {"UncertaintyBiasN", MxSFormatType.Uncertainty},
            {"UncertaintyBiasV", MxSFormatType.Uncertainty},
            {"UncertaintyCorrHL", MxSFormatType.UnitlessFourPrecision},
            {"UncertaintyCorrHA", MxSFormatType.UnitlessFourPrecision},
            {"UncertaintyCorrLA", MxSFormatType.UnitlessFourPrecision},
            {"UncertaintyCovEE", MxSFormatType.UncertaintyCovValue},
            {"UncertaintyCovEV", MxSFormatType.UncertaintyCovValue},
            {"UncertaintyCovNE", MxSFormatType.UncertaintyCovValue},
            {"UncertaintyCovNN", MxSFormatType.UncertaintyCovValue},
            {"UncertaintyCovNV", MxSFormatType.UncertaintyCovValue},
            {"UncertaintyCovVV", MxSFormatType.UncertaintyCovValue},
            {"UncertaintyHMajSA", MxSFormatType.Uncertainty},
            {"UncertaintyHMinSA", MxSFormatType.Uncertainty},
            {"UncertaintySemiAx1", MxSFormatType.Uncertainty},
            {"UncertaintySemiAx2", MxSFormatType.Uncertainty},
            {"UncertaintySemiAx3", MxSFormatType.Uncertainty},
            {"UncertaintyRotAng", MxSFormatType.Azimuth},
            {"TVDss", MxSFormatType.MeasuredDepthDistance },
            {"NorthSouth", MxSFormatType.MeasuredDepthDistance},
            {"EastWest", MxSFormatType.MeasuredDepthDistance},
            {"CourseLength", MxSFormatType.MeasuredDepthDistance}
        };
    }
}
